Document: xournal
Title: Debian xournal Manual
Author: <insert document author here>
Abstract: This manual describes what xournal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xournal/xournal.sgml.gz

Format: postscript
Files: /usr/share/doc/xournal/xournal.ps.gz

Format: text
Files: /usr/share/doc/xournal/xournal.text.gz

Format: HTML
Index: /usr/share/doc/xournal/html/index.html
Files: /usr/share/doc/xournal/html/*.html

  
