/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_winMain (void);
GtkWidget* create_fontDialog (void);
GtkWidget* create_colorChooserDialog (void);
GtkWidget* create_papersizeDialog (void);
GtkWidget* create_aboutDialog (void);
